name: Daily GA4 Update

on:
  schedule:
    - cron: '0 4 * * *'

  workflow_dispatch:

jobs:
  update-data:

    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Create oauth file
        run: |
          echo '${{ secrets.OAUTH_JSON }}' > oauth.json

      - name: Create service account file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > client_secret.json

      - name: Show files
        run: |
          ls

      - name: Run update script
        run: |
          python3 update_all.py
